### PR TITLE
Include copyright notice from zlib

### LINKED ISSUE #7: Clarify Licenses
The [Cargo.toml](https://github.com/remram44/adler32-rs/blob/master/Cargo.toml#L10) says this crate is BSD-3-Clause, but the [LICENSE](https://github.com/remram44/adler32-rs/blob/master/LICENSE) included is the MIT license, and the text of the library [includes the zlib license](https://github.com/remram44/adler32-rs/blob/master/src/lib.rs#L20).

Can you clarify this situation? Do all three licenses apply to the crate?
cc @jamesr

### PR DESCRIPTION
**Pull request by remram44**
Fixes #7

### CODE REVIEW

**Comment by remram44** [comment]
@jamesr @cramertj please confirm this works for you :wink:

**Comment by cramertj** [comment]
@remram44 I think you also want to add an entry in [Cargo.toml](https://github.com/remram44/adler32-rs/blob/master/Cargo.toml#L10).

**Comment by remram44** [comment]
I don't know what that entry should be. "BSD AND zlib" is inaccurate.

**Comment by jamesr** [comment]
Where can I find documentation on what can go into Cargo.toml files?

**Comment by cramertj** [comment]
@jamesr https://doc.rust-lang.org/cargo/reference/manifest.html#package-metadata specifies the behavior of the `license` key:

```
# This is an SPDX 2.1 license expression for this package.  Currently
# crates.io will validate the license provided against a whitelist of
# known license and exception identifiers from the SPDX license list
# 2.4.  Parentheses are not currently supported.
#
# Multiple licenses can be separated with a `/`, although that usage
# is deprecated.  Instead, use a license expression with AND and OR
# operators to get more explicit semantics.
```

**Comment by remram44** [comment]
So what would you have me do?

**Comment by jamesr** [comment]
I believe that parts of this crate are covered by the BSD license and parts by the zlib license and thus the terms of both apply, so an AND operator is accurate.  In other words, as a user of this crate I must consider both the BSD and zlib licenses.

**Comment by remram44** [comment]
Would that be enough? I'm not sure if I need to list to copyright holders in there, if I add the Zlib license, since I (listed `author` in `Cargo.toml`) am not the one granting you that license.

Or I am overthinking this?

**Comment by jamesr** [comment]
The change including 41954a5 works for me.  If I'm interpreting https://doc.rust-lang.org/cargo/reference/manifest.html#package-metadata correctly, the 'authors' field is not making a statement about copyright holders.  The license text itself has that information.

:+1:

**Pull request merged**
