### PR TITLE
Rust-styled update_buffer() and new combine() method

### PR DESCRIPTION
**Pull request by antonmarsden**
This is my attempt to improve baseline (multi-architecture) performance of adler32. In summary:
- additional benchmarks have been added for a range of buffer sizes
- do4() has been reimplemented with some bit shifting and u16 magic.
- update_buffer() has a significant performance boost, at least 30% faster for larger buffers but worth testing on other machines/platforms. I get 3600MB/s on my laptop, and 3400MB/s on a Pentium G4560 server.
- combine() has been implemented (based on zlib.c initially)
- Copy and Clone are implemented, some methods updated to use pass by value

Do with this pull request what you will :)

### CODE REVIEW

**Comment by antonmarsden** [comment]
Due to the failure of the 1.17.0 build, looks like it might need:
``
edition = "2018"
``
in Cargo.toml. But this messes up the benchmark config. :(

**Comment by remram44** [comment]
Don't worry about failure on 1.17.0, it's very old and I think we can drop support if needed (or at least give up on running benchmarks on that version)

**Comment by antonmarsden** [comment]
@remram44 I've simplified the code now, should be much easier to review.

**Comment by LingMan** [comment]
Hey @antonmarsden,

This looks pretty good and I'd like to see this land. Are you still interested in working on it? If not, I could take over.

On a high level all those intermediate commits should be squashed and split so you end up with
- One commit for the benchmarks (needs to be rebased onto master)
- One commit for the update_buffer changes
- Split out the new combine() method into it's own PR.

**Comment by antonmarsden** [comment]
@LingMan I am fairly busy at the moment, but totally agree with your assessment. Feel free to take the torch!

**Pull request closed without merging**
